---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    ADMIN: AgBYNrQBK7KS1Ayy+WfklS3M/05AQJc3tjQBONEYebAfwWHYzcmu1lo/xM1lvP0MwJ1Ckyve31w0Qgj4LDjD4whjAc62kofDQuR/jZltTNGzuRrmmADESrJcrt5DnlnsdLZh5OZp4iURhjph+QXVZyW9ieAiIGOLEcKIvOiVtLMMrDKLWhhMgALq5GnjlpMxP/YrQ0K03ubXe7Gbo8eZixLFKQGiuowcMvPr6fyyQiKy1Lgq5ZAsbWcDUC7k7JGBs3GceqRW8B+Dg2Gbe0OOuXdBvKnbBmi1rqNZphDbp5uyusfx8qF46YQFtBM+1BgR4GhKyor8yKbdpH2zWh0/Pe3lx79KgMaM4HxEELfpplOQv9+t4tKHThGVKOTgXM9iLgTQvbCj07EwqrFkAmnmGC4/nZmvLzN37KnHIW8K+h825c7MyBaABj6eb5EoHImD7R1BduWqLQAccxs1IHyrXFqJp6yG9lIDkjLhJnPzObT1ZO8wuAzHJpBsoolloaDYFyL1QbFeHmnge8PP7jAku3LnhgwhTxbO+TFw59x5VoclIGyi2tt/3xXKrx7o8ZtNaklGBEOAnMi569wrrq6sTeFkrdlEQ5Xs0tkh9CzF9exIS20l50fwl3zJFQ4A36qNpZwZBvlZPf61JxkSgS8mfIjhrAgHtCEbqKF5ofIhzT037o1VS68AQ7F4wu40Wv1/ww0fN2A0z3fL1NVv7Ihj
    DATABASE_PASSWORD: AgBx6t8YWXI1fI9VHzY8Zla5m3Zksg9jzkKW2BMClE+vW2JevNtWzDJEcrTembFypy+JE+WNh/liMwUBVRFB/Ee60BLmuWvBVGiu79RLmpF+WerJsIpU7Gj6Qg3swY7aypncxXXCFtP8iyOQiT7aA/I69j6W9dFM7QvgbhZjkQLj3s4CjqXxEhkRxfBC6vKTUzQJBj524jochCUgUoMmTZ3v+SCMXmy2PHYBlwY4rzTUfbdR5w9x6klZBUdbesMMDKxkO7KBlWTgD6s6gqHOpIQOopqmgH1BdsOp8Qv/b4l5YcvAubmXWAPcZRLz/K0RNiHG7nY7yy9/Ivul0IQ1DTf0S1QTXEXW4tyEqIgaUlTN4fqOA4UB8kJIYgrOlXVmZpKIZXjps+jlWR6aa3GY4H7JaqVkK1+MG4MUiN60Etc8rN103hpzyZpG6DtgkKXxn/L7wTfS4lcAtsloDalYyBw0uxHv7Symlf1/OxuZZpBPqCSbNvOfK6NfnnfvbbRbnMxzBWe5Q/UBcUsggRATE0zQnkCbbnSmjgVXQ7XR3kh103lBCdKgQ0+zaHkJlI40ir/hoRdkIub3IInw49lupCVgOPPCQbikfwogES7wfTJXporYtv5xcZs+l62MTr0+Niz6+4S9kWUfPS6sTo+0y7W5coxFWf9kR0qWz0+zYcDUgFetpZd+IrO2hGCWFwDPok0pZnbp57AAh/THV5FKXtJ1o74R5zU=
    JWT_SECRET: AgCTWm8022AvnO65KA0sn1N8r8Ceo2a7+uSd8AZCZ0LTwmOlH+WZp5fx36pC+rnHk8M7KCiPU0qmUK66+1C06QbfzB+MzasidnkXHtReHlDWSa6JZe5DUKmjdXl6VHPZHDRtiAdrD7QRTA5T+GI9GLttftV0BrMLWfuNnlUHVk8JKJ6sVpvcELeWgyJcIav9F4G/jcUrIu820o4SvCqdBH8pFwtA4UF0eBtZ0zfFlBpXo4xQl3blKKZNWHZNYspRWK5DXHISyD+3BbsBFK99DyvRnNh6jJ9yXDids+Eth521EiHQQJsO70+vhnvFy3uNg3pZi+nnj+f8jKeJKlMycm7mY1uWNZZrDVjDZRjWIvAnS0lmrL8kdC6zs4oBXYcOzml+tShXPoOc866vPmuPgNnYbqAAZ3ilvWa+tfQ7edzM4YNVmWJOxrm5sVxrxGBCsXITNrjjUA+RpTn0calSKgX7L3ZdDof1De9WLY7v8kq2lfn/0S1oARdoVldevwXCyWq0d5GmaWE+mUwx9sEQ9nShy5KCY8lOe+CmMcVAMzaol4b84OBDbPQOGcWLUsv8AFtePurtoigCXnYQmf0oMZ7rKFHnTJ5tFpGcLhQ9xYdWP6OPq866PwQFOvjVwIbFkM37MRTZWLQGoRncMZAVI0VVpSS5q7erJyYgIY7e1/9UO5cwDQM0d/SlOFcnM7n0HHqekmYKnwQQ6rZIc1Kp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
