name: Build, Push Docker Image, and Update Helm Values

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置 Docker 镜像标签
      - name: Set Docker image tag
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-7)"

      # 构建 Docker 镜像
      - name: Build Docker Image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }} .

      # 推送 Docker 镜像
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}

      # 更新 values.yaml 文件中的镜像信息
      - name: Update Helm values.yaml
        run: |
          sed -i 's|repository: .*|repository: '"${{ secrets.DOCKER_USERNAME }}/custom-nginx"'|' nginx-chart/values.yaml
          sed -i 's|tag: .*|tag: '"${{ steps.vars.outputs.sha_short }}"'|' nginx-chart/values.yaml

      # Debug: 确认 values.yaml 是否更新成功
      - name: Debug YAML Update
        run: cat nginx-chart/values.yaml

      # 配置 Git 信息
      - name: Set up Git config
        run: |
          git config user.name "walle45611"
          git config user.email "11146001@ntub.edu.tw"

      # 提交并推送更改到 GitHub
      - name: Commit and Push changes
        run: |
          git add nginx-chart/values.yaml
          git diff --cached --quiet || git commit -m "Update Helm values to ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}"
          git push origin main || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
