name: Build and Push Nginx

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 檢出你的專案
      - name: Checkout code
        uses: actions/checkout@v3

      # 登入 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 建構 Docker 映像
      - name: Build Docker Image
        run: |
          docker build -t  ${{ secrets.DOCKER_USERNAME }}/custom-nginx:latest .

      # 推送到 Docker Hub
      - name: Push Docker Image
        run: |
          docker push  ${{ secrets.DOCKER_USERNAME }}/custom-nginx:latest
