name: Build, Push Docker Image, and Update K8s Manifests

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置镜像标签
      - name: Set Docker image tag
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-7)"

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }} .

      # 推送 Docker 镜像
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}

      # 填写 `image` 字段为空的 `deployment.yaml`
      - name: Update Deployment YAML
        run: |
          sed -i '/container:/,/image:/ s|image: .*|image: '"${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}"'|' manifests/deployment.yaml

      # 配置 Git 用户信息
      - name: Set up Git config
        run: |
          git config user.name "walle45611"
          git config user.email "11146001@ntub.edu.tw"

      # 提交更新的文件
      - name: Commit and Push changes
        run: |
          git add manifests/deployment.yaml
          git commit -m "Update deployment image to ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
