name: Build, Push Docker Image, and Update K8s Manifests

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker image tag
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}

      - name: Update Deployment YAML
        run: |
          sed -i 's|image: .*|image: '"${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}"'|' manifests/deployment.yaml

      - name: Debug YAML Update
        run: cat manifests/deployment.yaml

      - name: Set up Git config
        run: |
          git config user.name "walle45611"
          git config user.email "11146001@ntub.edu.tw"

      - name: Commit and Push changes
        run: |
          git add manifests/deployment.yaml
          git commit -m "Update deployment image to ${{ secrets.DOCKER_USERNAME }}/custom-nginx:${{ steps.vars.outputs.sha_short }}"
          git push origin main || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
