apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: nginx.walle4561.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-service
                port:
                  number: {{ .Values.service.port }}
  tcp:
    5432:
      service:
        name: {{ .Release.Name }}-postgres-service
        port: 5432
