apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-my-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    POSTGRES_USER: {{ .Values.secrets.ADMIN }}
    POSTGRES_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD }}
