apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-my-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    ADMIN: {{ .Values.secrets.ADMIN }}
    DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD }}
    JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
