apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-my-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    ADMIN: {{ .Values.secrets.ADMIN }}
    DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD }}
    JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
